version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST:-db}  
      - DB_PORT=${DB_PORT:-5432}  
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST_PROD=${DB_HOST_PROD}
      - DB_PORT_PROD=${DB_PORT_PROD}
      - DB_USER_PROD=${DB_USER_PROD}
      - DB_PASSWORD_PROD=${DB_PASSWORD_PROD}
      - DB_NAME_PROD=${DB_NAME_PROD}
    env_file:
      - .env  
    depends_on:
      - db  

  db:
    image: postgres:latest
    ports:
      - "5430:5432"  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=aguura
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
